In [93]:
import warnings
warnings.filterwarnings('ignore')

In [94]:
# https://www.ritchieng.com/machine-learning-multinomial-naive-bayes-vectorization/

In [95]:
import pandas as pd

In [96]:
df=pd.read_excel('bizbuysell.single.large.ds.xlsx')

In [97]:
df.head()

Unnamed: 0       id      src   
0           0  2067319  details  \
1           1  1990890  details   
2           3  2039720  details   
3           4  1576680  details   
4           5  2087638  details   

                                                 url   
0  https://www.bizbuysell.com/Business-Real-Estat...  \
1  https://www.bizbuysell.com/Business-Real-Estat...   
2  https://www.bizbuysell.com/Business-Real-Estat...   
3  https://www.bizbuysell.com/Business-Real-Estat...   
4  https://www.bizbuysell.com/Business-Real-Estat...   

                                               title   
0  Popular Marina in Central New Jersey in Middle...  \
1  High Exposure in Mays Landing, New Jersey - Bi...   
2  Duplex, Short term or Long term in Pinellas Co...   
3  Major Price Reduction Rest/Tavern/ 13,000sq. f...   
4  Business & Real Estate in Casco, Michigan - Bi...   

                                                desc         local   
0  It is fully owned by a man and his wife since ...     Middlesex  \
1  AMAZING OPPORTUNITY! Priced to sell and ready ...  Mays Landing   
2  Rare Largo/Seminole area duplex centrally loca...      Pinellas   
3  Price reduced to $850. 000 MAKE AN OFFER!!!!!!...     Baltimore   
4  • The Business and the Real Estate are For Sal...         Casco   

       region                               location   
0  New Jersey                   Middlesex County, NJ  \
1  New Jersey     Mays Landing, NJ (Atlantic County)   
2     Florida                    Pinellas County, FL   
3    Maryland  Baltimore, MD (Baltimore City County)   
4    Michigan         Casco, MI (Saint Clair County)   

                                           title_loc  ...    price franchise   
0  Central New Jersey in Middlesex County, New Je...  ...  2500000     False  \
1                           Mays Landing, New Jersey  ...   225000     False   
2                           Pinellas County, Florida  ...   595000     False   
3                                Baltimore, Maryland  ...  1050000     False   
4                                    Casco, Michigan  ...   699900     False   

   lease auction   rent                             location_2  nationwide   
0  False   False  False                   Middlesex County, NJ       False  \
1  False   False  False     Mays Landing, NJ (Atlantic County)       False   
2  False   False  False                    Pinellas County, FL       False   
3  False   False  False  Baltimore, MD (Baltimore City County)       False   
4  False   False  False         Casco, MI (Saint Clair County)       False   

   multiple_locations  relocatable                               proc_loc  
0               False        False                   middlesex county, nj  
1               False        False     mays landing, nj (atlantic county)  
2               False        False                    pinellas county, fl  
3               False        False  baltimore, md (baltimore city county)  
4               False        False         casco, mi (saint clair county)  

[5 rows x 24 columns]

In [98]:
df=df[:1000]

In [99]:
df.shape

(1000, 24)

In [100]:
df

Unnamed: 0       id      src   
0             0  2067319  details  \
1             1  1990890  details   
2             3  2039720  details   
3             4  1576680  details   
4             5  2087638  details   
..          ...      ...      ...   
995        1036  1939664  details   
996        1037  2077739  details   
997        1038  2047395  details   
998        1039  2083749  details   
999        1040  2069277  details   

                                                   url   
0    https://www.bizbuysell.com/Business-Real-Estat...  \
1    https://www.bizbuysell.com/Business-Real-Estat...   
2    https://www.bizbuysell.com/Business-Real-Estat...   
3    https://www.bizbuysell.com/Business-Real-Estat...   
4    https://www.bizbuysell.com/Business-Real-Estat...   
..                                                 ...   
995  https://www.bizbuysell.com/Business-Real-Estat...   
996  https://www.bizbuysell.com/Business-Real-Estat...   
997  https://www.bizbuysell.com/Business-Real-Estat...   
998  https://www.bizbuysell.com/Business-Real-Estat...   
999  https://www.bizbuysell.com/Business-Real-Estat...   

                                                 title   
0    Popular Marina in Central New Jersey in Middle...  \
1    High Exposure in Mays Landing, New Jersey - Bi...   
2    Duplex, Short term or Long term in Pinellas Co...   
3    Major Price Reduction Rest/Tavern/ 13,000sq. f...   
4    Business & Real Estate in Casco, Michigan - Bi...   
..                                                 ...   
995  Downtown Lexingtion Sc. Commercial Building Si...   
996  2,500SF Commercial Building, Warehouse: Propos...   
997  Ocala Prime Commercial Building in Silver Spri...   
998  Restaurant at Syosset Center Mall in Syosset, ...   
999  Commercial Real Estate for Sale in Worcester, ...   

                                                  desc           local   
0    It is fully owned by a man and his wife since ...       Middlesex  \
1    AMAZING OPPORTUNITY! Priced to sell and ready ...    Mays Landing   
2    Rare Largo/Seminole area duplex centrally loca...        Pinellas   
3    Price reduced to $850. 000 MAKE AN OFFER!!!!!!...       Baltimore   
4    • The Business and the Real Estate are For Sal...           Casco   
..                                                 ...             ...   
995  Hard to find downtown Lexington 1.5 acre comme...       Lexington   
996  2,500SF +/- COMMMERCIAL WAREHOUSE $299,000POUG...    Poughkeepsie   
997  Rapidly Developing, Highly Desirable, Prime Oc...  Silver Springs   
998  The restaurant in a very clean and high-income...         Syosset   
999  Prime retail or office space in a condo office...       Worcester   

             region                               location   
0        New Jersey                   Middlesex County, NJ  \
1        New Jersey     Mays Landing, NJ (Atlantic County)   
2           Florida                    Pinellas County, FL   
3          Maryland  Baltimore, MD (Baltimore City County)   
4          Michigan         Casco, MI (Saint Clair County)   
..              ...                                    ...   
995  South Carolina       Lexington, SC (Lexington County)   
996        New York     Poughkeepsie, NY (Dutchess County)   
997         Florida     Silver Springs, FL (Marion County)   
998        New York            Syosset, NY (Nassau County)   
999   Massachusetts       Worcester, MA (Worcester County)   

                                             title_loc  ...    price   
0    Central New Jersey in Middlesex County, New Je...  ...  2500000  \
1                             Mays Landing, New Jersey  ...   225000   
2                             Pinellas County, Florida  ...   595000   
3                                  Baltimore, Maryland  ...  1050000   
4                                      Casco, Michigan  ...   699900   
..                                                 ...  ...      ...   
995                         

In [101]:
import numpy as np

In [102]:
df['label_rand'] = np.random.randint(0,2, size=len(df))

In [103]:
df['label_median']=df['price'].apply(lambda p: 1 if p > df['price'].mean() else 0)

In [104]:
df['label_q75']=df['price'].apply(lambda p: 1 if p > df['price'].quantile(.75) else 0)

In [105]:
df=df[['label_rand','label_median','label_q75','desc']]

In [106]:
df

label_rand  label_median  label_q75   
0             0             1          1  \
1             1             0          0   
2             1             0          0   
3             0             0          0   
4             0             0          0   
..          ...           ...        ...   
995           1             0          0   
996           1             0          0   
997           0             0          0   
998           0             0          0   
999           1             0          0   

                                                  desc  
0    It is fully owned by a man and his wife since ...  
1    AMAZING OPPORTUNITY! Priced to sell and ready ...  
2    Rare Largo/Seminole area duplex centrally loca...  
3    Price reduced to $850. 000 MAKE AN OFFER!!!!!!...  
4    • The Business and the Real Estate are For Sal...  
..                                                 ...  
995  Hard to find downtown Lexington 1.5 acre comme...  
996  2,500SF +/- COMMMERCIAL WAREHOUSE $299,000POUG...  
997  Rapidly Developing, Highly Desirable, Prime Oc...  
998  The restaurant in a very clean and high-income...  
999  Prime retail or office space in a condo office...  

[1000 rows x 4 columns]

In [107]:
X = df.desc
y = df.label_q75
print(X.shape)
print(y.shape)

(1000,)
(1000,)


In [108]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(750,)
(250,)
(750,)
(250,)


In [109]:
from sklearn.feature_extraction.text import CountVectorizer

In [110]:
# remove English stop words
# include 1-grams and 2-grams
# ignore terms that appear in more than 50% of the documents
# only keep terms that appear in at least 2 documents
vect = CountVectorizer(stop_words='english',ngram_range=(1, 2),max_df=0.5,min_df=20)

In [111]:
X_train_dtm = vect.fit_transform(X_train)

In [112]:
X_train_dtm

<750x8761 sparse matrix of type '<class 'numpy.int64'>'
	with 57502 stored elements in Compressed Sparse Row format>

In [113]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<250x8761 sparse matrix of type '<class 'numpy.int64'>'
	with 14716 stored elements in Compressed Sparse Row format>

In [114]:
from sklearn.naive_bayes import MultinomialNB

In [115]:
nb = MultinomialNB()

In [116]:
%time nb.fit(X_train_dtm, y_train)

CPU times: user 3.06 ms, sys: 1.67 ms, total: 4.72 ms
Wall time: 3.27 ms


MultinomialNB()

In [117]:
y_pred_class = nb.predict(X_test_dtm)

In [118]:
from sklearn import metrics

In [119]:
metrics.accuracy_score(y_test, y_pred_class)

0.768

In [120]:
# examine class distribution
print(y_test.value_counts())
# there is a majority class of 0 here, hence the classes are skewed

# calculate null accuracy (for multi-class classification problems)
# .head(1) assesses the value 1208
null_accuracy = y_test.value_counts().head(1) / len(y_test)
print('Null accuracy:', null_accuracy)

# Manual calculation of null accuracy by always predicting the majority class
print('Manual null accuracy:',(1208 / (1208 + 185)))

label_q75
0    189
1     61
Name: count, dtype: int64
Null accuracy: label_q75
0    0.756
Name: count, dtype: float64
Manual null accuracy: 0.8671931083991385


In [121]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[173,  16],
       [ 42,  19]])

In [122]:
# print message text for the false positives (ham incorrectly classified as spam)

X_test[y_pred_class > y_test]

345    3 bedroom home, 1500+ linear feet of reinforce...
600    The Redrock Country Inn consists of 42,689 SF ...
577    Established and operating gas station for sale...
453    Car wash by itself on 0.7 acres of land absent...
148    LAND - BUSINESS - HOMEGreat Package Deal:.2 ac...
457    NO Express wash in sight with great traffic 37...
331    Nice Branded gas station located on a busy roa...
255    Since early 2021, the Vermont innkeeping lands...
654    Self-Serve Car Wash and Laundromat for Sale. L...
950    Liquor store in an extremely good part of Maco...
2      Rare Largo/Seminole area duplex centrally loca...
581    Car wash with 2 self service buildings and a 1...
195    Reduced!!Great opportunity for owner operators...
974                    Detroit High Volume Liquor Store.
892    Retail Building for Sale Details:* This is a r...
250    Thayers Inn Hotel in Littleton NH is for sale ...
Name: desc, dtype: object

In [123]:
# print message text for the false negatives (spam incorrectly classified as ham)

X_test[y_pred_class < y_test]

368    21,000 SQ FT of Great development opportunity ...
647    The Sports Bar has embodied the spirit of the ...
78     Turn Key Business with Fee Simple Real Estate ...
872    Seller provides concrete, paving and trucking ...
94     PRIME PROPERTY! 13,138 Square Foot NW Metro Co...
35     This 24,618+/- building located on Southwester...
395    Luxury Home on 120+/- Acres For Sale$2,500,000...
822    Investment property in the Arbuckle Mountains....
17     This is a large, 15,521 sf, building, sited on...
241    This is a terrific opportunity to purchase a C...
843    La Cucaracha Restaurant business / tenant is i...
573    Located in Southwest Florida, this operation c...
335    An outstanding opportunity to purchase a long ...
267    Ready for new operator!  Recently updated with...
236    This is a wonderful little park that backs up ...
175                                    Gun and Ammo Shop
711    This is an industrial & Commercial parts manuf...
120    In the middle of the Gra

In [124]:
y_pred_prob = nb.predict_proba(X_test_dtm)[:, 1]
# calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.7052216150576807

# Logistic regression

In [125]:
from sklearn.linear_model import LogisticRegression

In [126]:
logreg = LogisticRegression()

In [127]:
%time logreg.fit(X_train_dtm, y_train)

CPU times: user 67.2 ms, sys: 3.6 ms, total: 70.8 ms
Wall time: 69.2 ms


LogisticRegression()

In [128]:
y_pred_class = logreg.predict(X_test_dtm)

In [129]:
y_pred_prob = logreg.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([9.86760325e-01, 4.58050972e-02, 1.14086892e-02, 1.06659319e-02,
       1.82002748e-01, 5.38987759e-02, 2.95901535e-02, 6.99537642e-03,
       7.56544822e-03, 1.52424430e-01, 1.43795118e-01, 7.59031437e-02,
       5.63568587e-01, 6.77702680e-01, 3.75410246e-02, 4.28202829e-03,
       1.67383302e-02, 1.62202093e-05, 6.91885020e-02, 6.90847858e-01,
       3.28753429e-01, 2.04002758e-02, 6.73719950e-04, 1.92978644e-03,
       1.23000687e-02, 4.01888482e-01, 1.57536909e-07, 3.36958452e-01,
       7.20794565e-04, 8.76806681e-01, 2.20194689e-04, 6.16279801e-02,
       2.06239599e-04, 1.19393034e-02, 7.43485655e-01, 8.22793962e-01,
       1.32444811e-01, 2.32285115e-04, 1.61711585e-02, 1.31531643e-02,
       1.89435298e-01, 1.35011839e-01, 1.03765763e-02, 2.62180641e-02,
       3.01135651e-02, 2.33654960e-01, 4.60397372e-03, 6.60473687e-01,
       2.60039777e-01, 1.49258477e-02, 3.45545446e-01, 9.69058526e-01,
       1.27899112e-01, 5.22176682e-02, 1.74880040e-01, 8.12662155e-04,
      

In [130]:
# calculate accuracy
metrics.accuracy_score(y_test, y_pred_class)

0.748

In [131]:
# calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.6808916644982219

# Examining model

In [132]:
# store the vocabulary of X_train
X_train_tokens = vect.get_feature_names_out()
len(X_train_tokens)

8761

In [133]:
# examine the first 50 tokens
print(X_train_tokens[0:50])

['00' '00 00' '00 pm' '000' '000 00' '000 000' '000 30' '000 35' '000 65'
 '000 acres' '000 annual' '000 annually' '000 approx' '000 btu'
 '000 building' '000 business' '000 cars' '000 cases' '000 cash' '000 day'
 '000 gallon' '000 gallons' '000 gals' '000 included' '000 includes'
 '000 information' '000 inside' '000 inventory' '000 lbs' '000 lottery'
 '000 million' '000 month' '000 monthly' '000 plus' '000 property'
 '000 real' '000 revenue' '000 room' '000 seller' '000 sf' '000 sq'
 '000 sqft' '000 square' '000 total' '000 turn' '000 vehicles' '000 week'
 '000 year' '000 yearasking' '000 yearly']


In [134]:
# examine the last 50 tokens
print(X_train_tokens[-50:])

['years great' 'years including' 'years independent' 'years later'
 'years left' 'years located' 'years location' 'years new' 'years newly'
 'years old' 'years operating' 'years owner' 'years owners'
 'years property' 'years reach' 'years ready' 'years restaurant'
 'years seller' 'years serving' 'years store' 'years strong'
 'years successful' 'years time' 'yellowstone' 'yellowstone national'
 'yelp' 'yes' 'york' 'york property' 'young' 'youtu' 'youtu nfxu7wrnn0q'
 'youtube' 'yr' 'zero' 'zion' 'zone' 'zoned' 'zoned c1' 'zoned commercial'
 'zoned general' 'zoned location' 'zoned mixed' 'zoned property' 'zones'
 'zoning' 'zoning allows' 'zoning includes' 'zoning property' 'zoo']


In [135]:
nb.feature_count_

array([[24.,  3.,  3., ...,  2.,  2.,  2.],
       [10.,  1.,  1., ...,  0.,  0.,  0.]])

In [136]:
nb.feature_count_.shape

(2, 8761)

In [137]:
# number of times each token appears across all HAM messages
ham_token_count = nb.feature_count_[0, :]
ham_token_count

array([24.,  3.,  3., ...,  2.,  2.,  2.])

In [138]:
# number of times each token appears across all SPAM messages
spam_token_count = nb.feature_count_[1, :]
spam_token_count

array([10.,  1.,  1., ...,  0.,  0.,  0.])

In [139]:
# create a DataFrame of tokens with their separate ham and spam counts
tokens = pd.DataFrame({'token':X_train_tokens, 'ham':ham_token_count, 'spam':spam_token_count}).set_index('token')
tokens.head()

ham   spam
token               
00       24.0   10.0
00 00     3.0    1.0
00 pm     3.0    1.0
000     261.0  168.0
000 00    8.0    4.0

In [140]:
# examine 5 random DataFrame rows
# random_state=6 is a seed for reproducibility
tokens.sample(5, random_state=6)

ham  spam
token                  
000 business  5.0   5.0
located main  7.0   0.0
2020 covid    1.0   1.0
bar food      2.0   0.0
boston        1.0   4.0

In [141]:
nb.class_count_

array([561., 189.])

In [142]:
# add 1 to ham and spam counts to avoid dividing by 0
tokens['ham'] = tokens.ham + 1
tokens['spam'] = tokens.spam + 1
tokens.sample(5, random_state=6)

ham  spam
token                  
000 business  6.0   6.0
located main  8.0   1.0
2020 covid    2.0   2.0
bar food      3.0   1.0
boston        2.0   5.0

In [143]:
# convert the ham and spam counts into frequencies
tokens['ham'] = tokens.ham / nb.class_count_[0]
tokens['spam'] = tokens.spam / nb.class_count_[1]
tokens.sample(5, random_state=6)

ham      spam
token                           
000 business  0.010695  0.031746
located main  0.014260  0.005291
2020 covid    0.003565  0.010582
bar food      0.005348  0.005291
boston        0.003565  0.026455

In [144]:
# calculate the ratio of spam-to-ham for each token
tokens['spam_ratio'] = tokens.spam / tokens.ham
tokens.sample(5, random_state=6)

ham      spam  spam_ratio
token                                       
000 business  0.010695  0.031746    2.968254
located main  0.014260  0.005291    0.371032
2020 covid    0.003565  0.010582    2.968254
bar food      0.005348  0.005291    0.989418
boston        0.003565  0.026455    7.420635

In [145]:
# examine the DataFrame sorted by spam_ratio
tokens.sort_values('spam_ratio', ascending=False)

ham      spam  spam_ratio
token                                             
consent             0.001783  0.047619   26.714286
inn suites          0.001783  0.047619   26.714286
pip                 0.001783  0.047619   26.714286
hedgestone          0.001783  0.047619   26.714286
agreement required  0.001783  0.037037   20.777778
...                      ...       ...         ...
table               0.030303  0.005291    0.174603
traffic count       0.033868  0.005291    0.156224
machine             0.033868  0.005291    0.156224
alf                 0.037433  0.005291    0.141345
office space        0.074866  0.005291    0.070673

[8761 rows x 3 columns]